project:
  type: website
  output-dir: docs

website:
  title: "PREMISE Database"
  site-url: https://rohitfarmer.github.io/premise-db/
  description: "At the NIAID Vaccine Research Center, the PREMISE (Pandemic REsponse REpository through Microbial and Immune Surveillance and Epidemiology) program was established to support pandemic preparedness and response."
  back-to-top-navigation: true
  navbar:
    background: primary
    right:
      - text: About
        file: about/index.qmd
  page-footer: 
    center: "Contact: premise@nih.gov"
    border: true
    background: dark
    left: |
      [Antibody Sequence Data Submission Form](https://forms.office.com/g/tR8csZrMxF)
  twitter-card: true
  open-graph: true

format:
  html:
    theme: 
      light: materia
    link-external-icon: true
    link-external-newwindow: true
    include-in-header:
      - text: |
          <meta name="robots" content="noindex, nofollow" />

editor: source


