project:
  type: website
  output-dir: docs

website:
  title: "PREMISE Databases"
  site-url: https://rohitfarmer.github.io/premise-db/
  description: "At the NIAID Vaccine Research Center, the PREMISE (Pandemic REsponse REpository through Microbial and Immune Surveillance and Epidemiology) program was established to support pandemic preparedness and response."
  back-to-top-navigation: true
  navbar:
    background: primary
    right:
      - text: Catalog
        file: catalog/index.qmd
      - text: News
        file: news.qmd
      - icon: github
        href: https://github.com/rohitfarmer/premise-db
  page-footer: 
    center: "Contact: premise@nih.gov"
    border: true
    background: dark
  twitter-card: true
  open-graph: true

format:
  html:
    theme: 
      light: cosmo
    link-external-icon: true
    link-external-newwindow: true
    include-in-header:
      - text: |
          <meta name="robots" content="noindex, nofollow" />

editor: source


