---
pagetitle: PREMISE Database
title-block-banner: false
comments: false
execute:
    echo: false
---

```{=html}
<br>
<br>

<p style="text-align: center;"><b>PREMISE (Pandemic REsponse REpository through Microbial and Immune Surveillance and Epidemiology)</b> Database is an extensive collection of monoclonal antibody sequences targeting pathogens of pandemic potential.</p>

<br>
<br>
<hr>
```




```{r}
#| warning: false
suppressMessages(library(tidyverse))
suppressMessages(library(readxl))
suppressMessages(library(DT))

dat <- read_excel(file.path("data", "premise-antibody-meta-data.xlsx"))
```

```{r}
#| column: screen-inset-shaded

dat %>%
    dplyr::mutate("Data Access" = paste0('<a href="', `Data Access`, '">', `Data Access`, '</a>')) %>% 
        DT::datatable(filter = 'top', escape = FALSE,
                      extensions = 'Buttons', # to add buttons to copy and download data as CSV and Excel files
                      options = list(dom = 'Blfrtip', buttons = c('excel')))
```

